import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:workout_notes/services/sleep_wake_engine.dart';
import 'package:workout_notes/services/smart_wake_policy.dart';
import 'support/sleep_bedside_fixture.dart';

/// The Android smart alarm runs a Kotlin copy of the causal sleep/wake filter
/// and of [SmartWakePolicy]. `test/fixtures/sleep_wake_parity.json` holds what
/// the Dart code computes on the real fixture nights; this test keeps it in
/// sync with Dart and `SleepWakeFilterParityTest.kt` holds Kotlin to it.
///
/// After an intended engine change, regenerate it with
/// `UPDATE_SLEEP_PARITY=1 flutter test test/sleep_wake_parity_test.dart`
/// and port the same change to `SleepWakeFilter.kt` / `SmartWakePolicy.kt`.
void main() {
  const goldenPath = 'test/fixtures/sleep_wake_parity.json';
  const runs = [
    ('sleep_quantized_bedside.json', 'audio-features-v3'),
    ('sleep_ambiguous_bedside.json', 'audio-features-v3'),
    ('sleep_dawn_bedside.json', 'audio-features-v4'),
    ('sleep_dawn_bedside.json', 'audio-features-v5'),
  ];

  Map<String, Object?> compute() => {
    'note':
        'Generated by test/sleep_wake_parity_test.dart. Causal sleep/wake '
        'probabilities and smart-alarm triggers of the fixture nights; the '
        'Kotlin copy must reproduce them.',
    'session_id': 'bedside',
    'start': bedsideStart.toIso8601String(),
    'runs': [for (final (file, version) in runs) _run(file, version)],
  };

  test('Dart sleep/wake filter matches the parity golden', () {
    final current = compute();
    final file = File(goldenPath);
    if (Platform.environment['UPDATE_SLEEP_PARITY'] == '1') {
      file.writeAsStringSync(jsonEncode(current));
    }
    final golden = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    final goldenRuns = golden['runs'] as List;
    final currentRuns = current['runs']! as List;
    expect(goldenRuns.length, currentRuns.length);
    for (var r = 0; r < currentRuns.length; r++) {
      final expected = goldenRuns[r] as Map<String, dynamic>;
      final actual = currentRuns[r] as Map<String, Object?>;
      final label = '${actual['fixture']} ${actual['feature_version']}';
      expect(expected['reason'], actual['reason'], reason: label);
      expect(expected['valid'], actual['valid'], reason: label);
      final p = expected['p'] as List;
      final q = actual['p']! as List<double>;
      expect(p.length, q.length, reason: label);
      for (var i = 0; i < q.length; i++) {
        expect(
          (p[i] as num).toDouble(),
          closeTo(q[i], 1e-12),
          reason: '$label window $i',
        );
      }
      expect(
        jsonEncode(expected['smart']),
        jsonEncode(actual['smart']),
        reason: label,
      );
    }
  });

  test('the smart alarm never rings before sleep or after the deadline', () {
    final policy = SmartWakePolicy(0.5);
    final deadline = bedsideStart.add(const Duration(hours: 1));
    final windowStart = deadline.subtract(const Duration(minutes: 30));
    String? feed(int i, double p) => policy.onWindow(
      sleepProbability: p,
      validSignal: true,
      seconds: 30,
      now: bedsideStart.add(Duration(seconds: 30 * (i + 1))),
      windowStart: windowStart,
      deadline: deadline,
    );

    // Awake and restless in the window before any sleep: not armed.
    for (var i = 60; i < 70; i++) {
      expect(feed(i, 0.1), isNull);
    }
    // 10 min of confident sleep arms it; still quiet, so nothing rings.
    for (var i = 70; i < 90; i++) {
      expect(feed(i, 0.95), isNull);
    }
    expect(policy.isArmed, isTrue);
    expect(feed(90, 0.6), isNull);
    expect(feed(91, 0.45), SmartWakePolicy.triggerStirring);
    expect(feed(92, 0.1), SmartWakePolicy.triggerAwake);
    // At or past the deadline the exact alarm owns the ring.
    expect(feed(119, 0.1), isNull);
    expect(feed(130, 0.1), isNull);
  });
}

Map<String, Object?> _run(String file, String version) {
  final segments = quantizedBedsideSegments(fileName: file);
  final cursor = SleepWakeCursor(
    sessionId: 'bedside',
    startsAwake: true,
    featureVersion: version,
  );
  final p = <double>[];
  final reasons = <String>[];
  final valid = <bool>[];
  for (final segment in segments) {
    final decision = cursor.add(segment);
    p.add(cursor.sleepProbability!);
    reasons.add(decision.reason);
    valid.add(decision.validSignal);
  }
  final ends = [
    for (final s in segments)
      s.startedAt.add(Duration(seconds: s.durationSeconds)),
  ];
  final smart = <Map<String, Object?>>[];
  for (final fraction in const [0.5, 0.75, 1.0]) {
    final deadline = ends[((ends.length - 1) * fraction).round()];
    for (final threshold in const [0.7, 0.5, 0.3]) {
      final policy = SmartWakePolicy(threshold);
      int? fired;
      String? trigger;
      for (var i = 0; i < segments.length && fired == null; i++) {
        final result = policy.onWindow(
          sleepProbability: p[i],
          validSignal: valid[i],
          seconds: segments[i].durationSeconds,
          now: ends[i],
          windowStart: deadline.subtract(const Duration(minutes: 30)),
          deadline: deadline,
        );
        if (result != null) {
          fired = i;
          trigger = result;
        }
      }
      smart.add({
        'window_minutes': 30,
        'threshold': threshold,
        'deadline_offset_seconds': deadline.difference(bedsideStart).inSeconds,
        'fired_index': fired,
        'trigger': trigger,
      });
    }
  }
  return {
    'fixture': file,
    'feature_version': version,
    'p': p,
    'reason': reasons,
    'valid': valid,
    'smart': smart,
  };
}
