version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      actions:
        update-types: ["minor", "patch"]

  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      pub-minor-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: gradle
    directory: "/android"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      gradle-minor-patch:
        update-types: ["minor", "patch"]
