import 'dart:math' as math;

import 'package:workout_notes/models/run_activity.dart';
import 'package:workout_notes/models/run_plan.dart';
import 'package:workout_notes/models/run_plan_workout.dart';
import 'package:workout_notes/models/scheduled_run.dart';
import 'package:workout_notes/repositories/run_plan_repository.dart';
import 'package:workout_notes/repositories/run_repository.dart';
import 'package:workout_notes/services/run_pace_calculator.dart';
import 'package:workout_notes/services/run_plan_adaptation.dart';
import 'package:workout_notes/services/run_plan_composer.dart';
import 'package:workout_notes/services/run_plan_templates.dart';

/// Weekly review of the plan being followed: turns what was actually run
/// into a [RunPlanAdaptationProposal], and applies it by re-planning the rest
/// of the plan with the composer.
///
/// The review never changes a plan on its own. It proposes; the athlete
/// applies or dismisses, once per plan week.
class RunPlanCoach {
  /// Key in the stored config: the plan week the current composition starts
  /// at, so the pace ramp can be read at the right offset after a re-plan.
  static const replannedFromWeekKey = 'replannedFromWeek';

  final RunPlanRepository _plans;
  final RunRepository _runs;

  RunPlanCoach({RunPlanRepository? plans, RunRepository? runs})
    : _plans = plans ?? RunPlanRepository(),
      _runs = runs ?? RunRepository();

  /// The suggestion for [plan]'s current week, or null when there is nothing
  /// to change, it was already answered, or the plan is not running.
  Future<RunPlanAdaptationProposal?> review(
    RunPlan plan, {
    DateTime? now,
  }) async {
    final today = now ?? DateTime.now();
    if (!plan.isActivated || plan.activatedAt == null) return null;
    final current = plan.activeWeekIndexOn(today);
    if (current == null || current >= plan.weeks) return null;
    final answered = await _plans.listAdaptations(plan.id);
    if (answered.any((a) => a.weekIndex == current)) return null;

    final data = await _load(plan, today);
    final proposal = RunPlanAdaptationEngine.propose(
      currentWeek: current,
      planWeeks: plan.weeks,
      currentWeekStarted: data.startedWeeks.contains(current),
      pastWeeks: data.reviews,
      expectedVdot: _expectedVdot(plan, current),
      fitness: data.fitness,
      now: today,
      fallbackBaselineKm: (plan.config?['currentWeeklyKm'] as num?)?.toDouble(),
    );
    return proposal.isEmpty ? null : proposal;
  }

  /// The athlete keeps the plan as it is for this week.
  Future<void> dismiss(RunPlan plan, RunPlanAdaptationProposal proposal) =>
      _plans.recordAdaptation(
        planId: plan.id,
        weekIndex: proposal.weekIndex,
        kind: proposal.adjustment.name,
        status: 'dismissed',
        payload: _payload(proposal),
      );

  /// Re-plans [plan] from [RunPlanAdaptationProposal.fromWeek] on.
  ///
  /// Plans generated by the catalog are re-composed: same template and
  /// wizard inputs, with the new starting volume, the new fitness estimate
  /// and the weeks actually left. Blank or pre-v52 plans have no inputs to
  /// re-compose from, so only the next week's volume is scaled.
  Future<void> apply(
    RunPlan plan,
    RunPlanAdaptationProposal proposal, {
    DateTime? now,
  }) async {
    final today = now ?? DateTime.now();
    final config = RunPlanBuildConfig.fromJson(plan.config);
    final template = plan.templateKey == null
        ? null
        : RunPlanTemplates.byKey(plan.templateKey!);
    final anchor = plan.activatedAt;
    if (config != null && template != null && anchor != null) {
      final scheduled = await _plans.getScheduledRunsForPlan(plan.id);
      final testDone = scheduled.any(
        (s) =>
            s.workout?.kind == RunWorkoutKind.test &&
            (s.isCompleted || s.date.isBefore(today)),
      );
      final next = _replanConfig(
        plan: plan,
        config: config,
        proposal: proposal,
        startWeek: _weekStart(
          anchor,
        ).add(Duration(days: 7 * proposal.fromWeek)),
        includeTest: config.includeTest && !testDone,
      );
      final outline = RunPlanComposer.outline(template, next);
      await _plans.replaceWeeksFrom(
        plan.id,
        fromWeek: proposal.fromWeek,
        weeks: [for (final week in outline.schedule) _drafts(week)],
        config: {...next.toJson(), replannedFromWeekKey: proposal.fromWeek},
      );
    } else if (proposal.baselineKm != null && proposal.fromWeek < plan.weeks) {
      final planned = plan.weeklyDistanceMeters(proposal.fromWeek) / 1000;
      if (planned > 0 && proposal.baselineKm! < planned) {
        await _plans.scaleWeek(
          plan.id,
          proposal.fromWeek,
          proposal.baselineKm! / planned,
        );
      }
    }
    await _plans.recordAdaptation(
      planId: plan.id,
      weekIndex: proposal.weekIndex,
      kind: proposal.adjustment.name,
      status: 'applied',
      payload: _payload(proposal),
    );
  }

  RunPlanBuildConfig _replanConfig({
    required RunPlan plan,
    required RunPlanBuildConfig config,
    required RunPlanAdaptationProposal proposal,
    required DateTime startWeek,
    required bool includeTest,
  }) {
    final fitness = proposal.newVdot ?? proposal.expectedVdot;
    final baseline =
        proposal.baselineKm ??
        // Pace-only change: keep the volume the plan had for this week.
        plan.weeklyDistanceMeters(proposal.fromWeek) / 1000;
    return config.copyWith(
      // Training restarts from the fitness the athlete has now; the goal, if
      // any, stays where it was.
      calibration: fitness == null
          ? config.calibration
          : RunPlanPaceCalibration.fromVdot(fitness),
      paceSource: fitness == null
          ? config.paceSource
          : RunPlanPaceSource.recent,
      goalCalibration: config.goalTime,
      currentWeeklyKm: baseline > 0 ? baseline : config.currentWeeklyKm,
      startDate: startWeek,
      remainingWeeks: proposal.remainingWeeks,
      includeTest: includeTest,
    );
  }

  /// Fitness the plan's pace ramp expects for [week], when the plan knows its
  /// inputs.
  static double? _expectedVdot(RunPlan plan, int week) {
    final config = RunPlanBuildConfig.fromJson(plan.config);
    final key = plan.templateKey;
    if (config == null || key == null) return null;
    final template = RunPlanTemplates.byKey(key);
    if (template == null) return null;
    final from = (plan.config?[replannedFromWeekKey] as num?)?.toInt() ?? 0;
    try {
      return RunPlanComposer.paceRamp(
        template,
        config,
      ).vdotAt(math.max(0, week - from));
    } catch (_) {
      return null;
    }
  }

  Future<_ReviewData> _load(RunPlan plan, DateTime today) async {
    final anchor = _weekStart(plan.activatedAt!);
    final scheduled = await _plans.getScheduledRunsForPlan(plan.id);
    final activities = (await _runs.listActivities(
      limit: 400,
    )).where((a) => !a.startedAt.isBefore(anchor)).toList();
    final byId = {for (final a in activities) a.id: a};
    final current = plan.activeWeekIndexOn(today) ?? 0;

    final rowsByWeek = <int, List<ScheduledRun>>{};
    for (final row in scheduled) {
      final week = row.workout?.weekIndex;
      if (week == null) continue;
      rowsByWeek.putIfAbsent(week, () => []).add(row);
    }
    final started = <int>{
      for (final entry in rowsByWeek.entries)
        if (entry.value.any((r) => !r.isPlanned)) entry.key,
    };

    final reviews = <RunPlanWeekReview>[];
    for (var week = math.max(0, current - 4); week < current; week++) {
      final rows = rowsByWeek[week];
      // A week that was never on the calendar (plan activated mid-way) was
      // never the athlete's to run.
      if (rows == null || rows.isEmpty) continue;
      final start = anchor.add(Duration(days: 7 * week));
      final end = start.add(const Duration(days: 7));
      final ran = activities
          .where(
            (a) => !a.startedAt.isBefore(start) && a.startedAt.isBefore(end),
          )
          .toList();
      final linkedKinds = <String, RunWorkoutKind>{
        for (final r in rows)
          if (r.runActivityId != null && r.workout != null)
            r.runActivityId!: r.workout!.kind,
      };
      final easyRpe = [
        for (final a in ran)
          if (a.rpe != null &&
              const {
                RunWorkoutKind.easy,
                RunWorkoutKind.recovery,
                RunWorkoutKind.long,
              }.contains(linkedKinds[a.id]))
            a.rpe!,
      ];
      final sessions = plan.workoutsForWeek(week);
      reviews.add(
        RunPlanWeekReview(
          weekIndex: week,
          weekStart: start,
          plannedKm: plan.weeklyDistanceMeters(week) / 1000,
          doneKm: ran.fold<double>(0, (s, a) => s + a.distanceMeters / 1000),
          plannedSessions: sessions.length,
          doneSessions: rows.where((r) => r.isCompleted).length,
          qualityPlanned: sessions.where((s) => s.kind.isQuality).length,
          qualityDone: rows
              .where(
                (r) => r.isCompleted && (r.workout?.kind.isQuality ?? false),
              )
              .length,
          easyRpe: easyRpe.isEmpty
              ? null
              : easyRpe.reduce((a, b) => a + b) / easyRpe.length,
          maxedOutRuns: ran.where((a) {
            final kind = linkedKinds[a.id];
            return (a.rpe ?? 0) >= 9 &&
                kind != RunWorkoutKind.race &&
                kind != RunWorkoutKind.test;
          }).length,
          badFeelingRuns: ran
              .where((a) => a.feelingRating != null && a.feelingRating! <= 2)
              .length,
        ),
      );
    }

    return _ReviewData(
      reviews: reviews,
      startedWeeks: started,
      fitness: await _fitnessSamples(scheduled, byId, activities, today),
    );
  }

  Future<List<RunFitnessSample>> _fitnessSamples(
    List<ScheduledRun> scheduled,
    Map<String, RunActivity> byId,
    List<RunActivity> activities,
    DateTime today,
  ) async {
    final since = today.subtract(const Duration(days: 21));
    final samples = <RunFitnessSample>[];
    for (final row in scheduled) {
      final kind = row.workout?.kind;
      final activity = row.runActivityId == null
          ? null
          : byId[row.runActivityId];
      if (!row.isCompleted || activity == null || kind == null) continue;
      if (activity.startedAt.isBefore(since)) continue;
      final steps = await _plans.getActivitySteps(activity.id);
      final work = steps.where((s) => s.role == 'work').toList();
      switch (kind) {
        case RunWorkoutKind.test || RunWorkoutKind.race:
          final distance = work.isEmpty
              ? activity.distanceMeters
              : work.fold<double>(
                  0,
                  (s, w) => s + (w.actualDistanceMeters ?? 0),
                );
          final seconds = work.isEmpty
              ? activity.movingTimeSeconds
              : work.fold<int>(0, (s, w) => s + (w.actualDurationSeconds ?? 0));
          final sample = RunFitnessSample.fromResult(
            date: activity.startedAt,
            distanceMeters: distance,
            seconds: seconds,
            source: kind == RunWorkoutKind.test
                ? RunFitnessSource.test
                : RunFitnessSource.race,
          );
          if (sample != null) samples.add(sample);
        case RunWorkoutKind.interval || RunWorkoutKind.tempo:
          // An all-out effort on a threshold day says little about fitness.
          if ((activity.rpe ?? 0) >= 10) continue;
          final sample = RunFitnessSample.fromWorkPaces(
            date: activity.startedAt,
            paces: [
              for (final w in work)
                if (w.actualPaceSecPerKm != null) w.actualPaceSecPerKm!,
            ],
            fractionOfVo2Max: kind == RunWorkoutKind.interval ? 0.98 : 0.88,
          );
          if (sample != null) samples.add(sample);
        default:
          break;
      }
    }
    for (final activity in activities) {
      if (activity.startedAt.isBefore(since)) continue;
      for (final (meters, seconds) in [
        (3000.0, activity.bestEffort3kSec),
        (RunPaceCalculator.fiveKMeters, activity.bestEffort5kSec),
        (RunPaceCalculator.tenKMeters, activity.bestEffort10kSec),
      ]) {
        if (seconds == null) continue;
        final sample = RunFitnessSample.fromResult(
          date: activity.startedAt,
          distanceMeters: meters,
          seconds: seconds,
          source: RunFitnessSource.bestEffort,
        );
        if (sample != null) samples.add(sample);
      }
    }
    return samples;
  }

  static List<RunPlanSessionDraft> _drafts(List<RunPlanTemplateWorkout> week) =>
      [
        for (final session in week)
          RunPlanSessionDraft(
            workout: {
              'day_of_week': session.dayOfWeek,
              'kind': session.kind.value,
              'name': session.name,
              'notes': session.notes,
              'effort_zone': session.effortZone,
              'target_distance_meters': session.targetDistanceMeters,
              'target_duration_seconds': session.targetDurationSeconds,
              'target_pace_sec_per_km': session.targetPaceSecPerKm,
            },
            steps: [
              for (final step in session.steps)
                {
                  'role': step.role.value,
                  'metric': step.metric.name,
                  'value': step.value,
                  'repeat_group': step.repeatGroup,
                  'repeat_count': step.repeatCount,
                  'target_pace_min_sec_per_km': step.targetPaceMinSecPerKm,
                  'target_pace_max_sec_per_km': step.targetPaceMaxSecPerKm,
                },
            ],
          ),
      ];

  static Map<String, dynamic> _payload(RunPlanAdaptationProposal p) => {
    'adjustment': p.adjustment.name,
    'fromWeek': p.fromWeek,
    'missedWeeks': p.missedWeeks,
    'baselineKm': p.baselineKm,
    'expectedVdot': p.expectedVdot,
    'newVdot': p.newVdot,
    'paceSource': p.paceSource?.name,
    if (p.lastWeek != null) ...{
      'doneKm': p.lastWeek!.doneKm,
      'plannedKm': p.lastWeek!.plannedKm,
    },
  };

  static DateTime _weekStart(DateTime date) {
    final day = DateTime(date.year, date.month, date.day);
    return day.subtract(Duration(days: day.weekday - 1));
  }
}

class _ReviewData {
  final List<RunPlanWeekReview> reviews;
  final Set<int> startedWeeks;
  final List<RunFitnessSample> fitness;

  const _ReviewData({
    required this.reviews,
    required this.startedWeeks,
    required this.fitness,
  });
}
