import 'package:sqflite/sqflite.dart';

/// Incremental database upgrades extracted from the legacy schema versions.
abstract final class DatabaseCatalogV11Migrations {
  static Future<void> upgrade(Database db, int oldVersion) async {
    if (oldVersion < 11) {
      final newExercises = [
        {
          'id': 'db_fly',
          'name': 'Crucifixo com Halteres',
          'locale_key': 'db_fly',
          'category_id': 'chest',
          'type': 'weightReps',
          'notes': 'Deitado no banco, halteres abertos e fechando no centro',
          'equipment': 'Dumbbell',
          'default_rest_time': 60,
          'weight_increment': 1.0,
        },
        {
          'id': 'pullover',
          'name': 'Pullover',
          'locale_key': 'pullover',
          'category_id': 'chest',
          'type': 'weightReps',
          'notes': 'Deitado no banco, halter atrás da cabeça',
          'equipment': 'Dumbbell',
          'default_rest_time': 90,
          'weight_increment': 2.0,
        },
        {
          'id': 'straight_arm_pulldown',
          'name': 'Puxada Braço Reto',
          'locale_key': 'straight_arm_pulldown',
          'category_id': 'back',
          'type': 'weightReps',
          'notes': 'Polia alta, braços esticados puxando até a coxa',
          'equipment': 'Cable',
          'default_rest_time': 60,
          'weight_increment': 2.5,
        },
        {
          'id': 'good_morning',
          'name': 'Good Morning',
          'locale_key': 'good_morning',
          'category_id': 'back',
          'type': 'weightReps',
          'notes': 'Barra nas costas, tronco inclinando para frente',
          'equipment': 'Barbell',
          'default_rest_time': 90,
          'weight_increment': 2.5,
        },
        {
          'id': 'inverted_row',
          'name': 'Remada Invertida',
          'locale_key': 'inverted_row',
          'category_id': 'back',
          'type': 'weightReps',
          'notes': 'Barra baixa, puxar o peito até a barra',
          'equipment': 'Bodyweight',
          'default_rest_time': 60,
          'weight_increment': 0,
        },
        {
          'id': 'cable_lat_raise',
          'name': 'Elevação Lateral na Polia',
          'locale_key': 'cable_lat_raise',
          'category_id': 'shoulders',
          'type': 'weightReps',
          'notes': 'Polia baixa, elevar lateralmente',
          'equipment': 'Cable',
          'default_rest_time': 60,
          'weight_increment': 1.0,
        },
        {
          'id': 'machine_ohp',
          'name': 'Desenvolvimento na Máquina',
          'locale_key': 'machine_ohp',
          'category_id': 'shoulders',
          'type': 'weightReps',
          'notes': 'Máquina de ombro sentado',
          'equipment': 'Machine',
          'default_rest_time': 90,
          'weight_increment': 2.5,
        },
        {
          'id': 'landmine_press',
          'name': 'Desenvolvimento com Barra no Chão',
          'locale_key': 'landmine_press',
          'category_id': 'shoulders',
          'type': 'weightReps',
          'notes': 'Barra apoiada no chão, pressionar em ângulo',
          'equipment': 'Barbell',
          'default_rest_time': 90,
          'weight_increment': 2.5,
        },
        {
          'id': 'incline_curl',
          'name': 'Rosca Inclinada',
          'locale_key': 'incline_curl',
          'category_id': 'biceps',
          'type': 'weightReps',
          'notes': 'Banco inclinado a 45°, braços pendurados para trás',
          'equipment': 'Dumbbell',
          'default_rest_time': 60,
          'weight_increment': 1.0,
        },
        {
          'id': 'reverse_curl',
          'name': 'Rosca Inversa',
          'locale_key': 'reverse_curl',
          'category_id': 'biceps',
          'type': 'weightReps',
          'notes': 'Barra com pegada pronada, foco no braquial',
          'equipment': 'Barbell',
          'default_rest_time': 60,
          'weight_increment': 1.0,
        },
        {
          'id': 'spider_curl',
          'name': 'Rosca Spider',
          'locale_key': 'spider_curl',
          'category_id': 'biceps',
          'type': 'weightReps',
          'notes': 'Banco inclinado, braços pendurados na vertical',
          'equipment': 'Dumbbell',
          'default_rest_time': 60,
          'weight_increment': 1.0,
        },
        {
          'id': 'overhead_cable_ext',
          'name': 'Tríceps Polia Alta',
          'locale_key': 'overhead_cable_ext',
          'category_id': 'triceps',
          'type': 'weightReps',
          'notes': 'Corda ou barra atrás da cabeça, estender acima',
          'equipment': 'Cable',
          'default_rest_time': 60,
          'weight_increment': 2.5,
        },
        {
          'id': 'single_pushdown',
          'name': 'Tríceps Polia Unilateral',
          'locale_key': 'single_pushdown',
          'category_id': 'triceps',
          'type': 'weightReps',
          'notes': 'Cada braço de cada vez, maior foco',
          'equipment': 'Cable',
          'default_rest_time': 60,
          'weight_increment': 1.0,
        },
        {
          'id': 'diamond_pushup',
          'name': 'Flexão Diamante',
          'locale_key': 'diamond_pushup',
          'category_id': 'triceps',
          'type': 'weightReps',
          'notes': 'Mãos juntas formando um diamante, foco no tríceps',
          'equipment': 'Bodyweight',
          'default_rest_time': 60,
          'weight_increment': 0,
        },
        {
          'id': 'adductor_machine',
          'name': 'Máquina de Adutor',
          'locale_key': 'adductor_machine',
          'category_id': 'legs',
          'type': 'weightReps',
          'notes': 'Fechar as pernas contra a resistência',
          'equipment': 'Machine',
          'default_rest_time': 60,
          'weight_increment': 2.5,
        },
        {
          'id': 'abductor_machine',
          'name': 'Máquina de Abdutor',
          'locale_key': 'abductor_machine',
          'category_id': 'legs',
          'type': 'weightReps',
          'notes': 'Abrir as pernas contra a resistência',
          'equipment': 'Machine',
          'default_rest_time': 60,
          'weight_increment': 2.5,
        },
        {
          'id': 'seated_calf',
          'name': 'Panturrilha Sentado',
          'locale_key': 'seated_calf',
          'category_id': 'legs',
          'type': 'weightReps',
          'notes': 'Joelhos a 90°, elevar os calcanhares',
          'equipment': 'Machine',
          'default_rest_time': 60,
          'weight_increment': 5.0,
        },
        {
          'id': 'glute_bridge',
          'name': 'Ponte de Glúteo',
          'locale_key': 'glute_bridge',
          'category_id': 'legs',
          'type': 'weightReps',
          'notes': 'Deitado, joelhos flexionados, elevar o quadril',
          'equipment': 'Bodyweight',
          'default_rest_time': 60,
          'weight_increment': 0,
        },
        {
          'id': 'step_up',
          'name': 'Step Up',
          'locale_key': 'step_up',
          'category_id': 'legs',
          'type': 'weightReps',
          'notes': 'Subir em um banco ou caixa, halteres nas mãos',
          'equipment': 'Dumbbell',
          'default_rest_time': 60,
          'weight_increment': 2.0,
        },
        {
          'id': 'nordic_curl',
          'name': 'Flexão Nórdica',
          'locale_key': 'nordic_curl',
          'category_id': 'legs',
          'type': 'weightReps',
          'notes': 'Joelhos no chão, pés presos, descer controlado',
          'equipment': 'Bodyweight',
          'default_rest_time': 90,
          'weight_increment': 0,
        },
        {
          'id': 'reverse_lunge',
          'name': 'Afundo Reverso',
          'locale_key': 'reverse_lunge',
          'category_id': 'legs',
          'type': 'weightReps',
          'notes': 'Passo para trás em vez de frente',
          'equipment': 'Dumbbell',
          'default_rest_time': 60,
          'weight_increment': 2.0,
        },
        {
          'id': 'side_plank',
          'name': 'Prancha Lateral',
          'locale_key': 'side_plank',
          'category_id': 'core',
          'type': 'timeOnly',
          'notes': 'Corpo reto de lado, antebraço no chão',
          'equipment': 'Bodyweight',
          'default_rest_time': 45,
          'weight_increment': 0,
        },
        {
          'id': 'bicycle_crunch',
          'name': 'Abdominal Bicicleta',
          'locale_key': 'bicycle_crunch',
          'category_id': 'core',
          'type': 'weightReps',
          'notes': 'Deitado, joelho ao cotovelo oposto alternado',
          'equipment': 'Bodyweight',
          'default_rest_time': 45,
          'weight_increment': 0,
        },
        {
          'id': 'reverse_crunch',
          'name': 'Reverse Crunch',
          'locale_key': 'reverse_crunch',
          'category_id': 'core',
          'type': 'weightReps',
          'notes': 'Elevar o quadril do chão contraindo o abdômen',
          'equipment': 'Bodyweight',
          'default_rest_time': 45,
          'weight_increment': 0,
        },
        {
          'id': 'dead_bug',
          'name': 'Dead Bug',
          'locale_key': 'dead_bug',
          'category_id': 'core',
          'type': 'weightReps',
          'notes': 'Braço e perna opostos estendendo simultaneamente',
          'equipment': 'Bodyweight',
          'default_rest_time': 45,
          'weight_increment': 0,
        },
        {
          'id': 'pallof_press',
          'name': 'Pallof Press',
          'locale_key': 'pallof_press',
          'category_id': 'core',
          'type': 'weightReps',
          'notes': 'Polia lateral, empurrar para frente sem girar o tronco',
          'equipment': 'Cable',
          'default_rest_time': 60,
          'weight_increment': 2.5,
        },
        {
          'id': 'elliptical',
          'name': 'Elíptico',
          'locale_key': 'elliptical',
          'category_id': 'cardio',
          'type': 'distanceTime',
          'notes': '',
          'equipment': 'Machine',
          'default_rest_time': 0,
          'weight_increment': 0,
        },
        {
          'id': 'stair_climber',
          'name': 'Escada',
          'locale_key': 'stair_climber',
          'category_id': 'cardio',
          'type': 'timeOnly',
          'notes': 'Simulador de escada',
          'equipment': 'Machine',
          'default_rest_time': 0,
          'weight_increment': 0,
        },
        {
          'id': 'burpee',
          'name': 'Burpee',
          'locale_key': 'burpee',
          'category_id': 'cardio',
          'type': 'weightReps',
          'notes': 'Agachar, pular para trás, flexão, voltar e saltar',
          'equipment': 'Bodyweight',
          'default_rest_time': 60,
          'weight_increment': 0,
        },
        {
          'id': 'battle_ropes',
          'name': 'Corda de Batalha',
          'locale_key': 'battle_ropes',
          'category_id': 'cardio',
          'type': 'timeOnly',
          'notes': 'Ondular as cordas alternadamente ou simultaneamente',
          'equipment': 'Bodyweight',
          'default_rest_time': 60,
          'weight_increment': 0,
        },
      ];
      for (final ex in newExercises) {
        try {
          await db.insert('exercises', {
            'id': ex['id'],
            'name': ex['name'],
            'locale_key': ex['locale_key'],
            'category_id': ex['category_id'],
            'type': ex['type'],
            'notes': ex['notes'],
            'equipment': ex['equipment'],
            'is_favorite': 0,
            'default_rest_time': ex['default_rest_time'],
            'weight_increment': ex['weight_increment'],
            'created_at': DateTime.now().toIso8601String(),
          }, conflictAlgorithm: ConflictAlgorithm.ignore);
        } catch (_) {}
      }
    }
  }
}
