from __future__ import annotations

import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont, ImageOps


ROOT = Path(__file__).resolve().parents[1]

SRC_ICON = ROOT / "store_assets/source/workout_notes_icon_imagegen.png"
SRC_FEATURE = ROOT / "store_assets/source/workout_notes_feature_imagegen.png"
SRC_REFERENCE = ROOT / "store_assets/source/app_reference_dashboard.png"

BG = (9, 14, 16)
SURFACE = (21, 27, 30)
SURFACE_2 = (31, 38, 43)
STROKE = (41, 50, 55)
TEXT = (222, 229, 233)
MUTED = (166, 177, 184)
CYAN = (108, 207, 246)
CYAN_DEEP = (0, 95, 115)
AMBER = (255, 176, 0)


def hex_color(rgb: tuple[int, int, int]) -> str:
    return "#{:02X}{:02X}{:02X}".format(*rgb)


def ensure_dirs() -> None:
    for rel in [
        "assets/brand",
        "android/app/src/main/res/mipmap-anydpi-v26",
        "store_assets/google_play",
        "store_assets/screenshots",
        "store_assets/source",
    ]:
        (ROOT / rel).mkdir(parents=True, exist_ok=True)


def font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    candidates = [
        "C:/Windows/Fonts/segoeuib.ttf" if bold else "C:/Windows/Fonts/segoeui.ttf",
        "C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf",
    ]
    for candidate in candidates:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def text(draw: ImageDraw.ImageDraw, xy, value: str, size: int, fill=TEXT, bold: bool = False, anchor=None) -> None:
    draw.text(xy, value, font=font(size, bold), fill=fill, anchor=anchor)


def wrap(draw: ImageDraw.ImageDraw, value: str, size: int, max_width: int, bold: bool = False) -> list[str]:
    words = value.split()
    lines: list[str] = []
    current = ""
    fnt = font(size, bold)
    for word in words:
        candidate = word if not current else f"{current} {word}"
        if draw.textbbox((0, 0), candidate, font=fnt)[2] <= max_width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def paragraph(draw: ImageDraw.ImageDraw, xy, value: str, size: int, max_width: int, fill=MUTED, bold: bool = False, gap: int = 10) -> int:
    x, y = xy
    for line in wrap(draw, value, size, max_width, bold):
        text(draw, (x, y), line, size, fill, bold)
        y += size + gap
    return y


def rounded(draw: ImageDraw.ImageDraw, box, radius: int, fill, outline=None, width: int = 1) -> None:
    draw.rounded_rectangle(box, radius=radius, fill=fill, outline=outline, width=width)


def fit(path: Path, size: tuple[int, int]) -> Image.Image:
    return ImageOps.fit(Image.open(path).convert("RGB"), size, method=Image.Resampling.LANCZOS, centering=(0.5, 0.5))


def contain(path: Path, size: tuple[int, int], color=BG) -> Image.Image:
    return ImageOps.contain(Image.open(path).convert("RGB"), size, method=Image.Resampling.LANCZOS)


def overlay_gradient(img: Image.Image, left_alpha: int = 205, right_alpha: int = 30) -> Image.Image:
    w, h = img.size
    gradient = Image.new("L", (w, 1))
    pixels = gradient.load()
    for x in range(w):
        t = x / max(1, w - 1)
        pixels[x, 0] = round(left_alpha * (1 - t) + right_alpha * t)
    gradient = gradient.resize((w, h))
    layer = Image.new("RGBA", (w, h), (*BG, 255))
    layer.putalpha(gradient)
    return Image.alpha_composite(img.convert("RGBA"), layer)


def add_vignette(img: Image.Image, strength: int = 120) -> Image.Image:
    w, h = img.size
    mask = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(mask)
    d.ellipse((-w // 5, -h // 2, w + w // 5, h + h // 2), fill=255)
    mask = ImageOps.invert(mask.filter(ImageFilter.GaussianBlur(w // 5)))
    shade = Image.new("RGBA", (w, h), (0, 0, 0, strength))
    shade.putalpha(mask)
    return Image.alpha_composite(img.convert("RGBA"), shade)


def icon_canvas(size: int, safe: float = 0.0, rgb: bool = False) -> Image.Image:
    src = Image.open(SRC_ICON).convert("RGB")
    # Keep the icon generated by imagegen intact, but add safe padding for launcher masks.
    if safe:
        inner = round(size * (1 - safe * 2))
        icon = ImageOps.contain(src, (inner, inner), Image.Resampling.LANCZOS)
        bg = fit(SRC_ICON, (size, size)).filter(ImageFilter.GaussianBlur(max(2, size // 28)))
        bg = Image.blend(Image.new("RGB", (size, size), BG), bg, 0.42)
        x = (size - icon.width) // 2
        y = (size - icon.height) // 2
        bg.paste(icon, (x, y))
        out = bg
    else:
        out = ImageOps.fit(src, (size, size), method=Image.Resampling.LANCZOS)
    return out.convert("RGB" if rgb else "RGBA")


def icon_cutout(size: int, safe: float = 0.0, rgb: bool = False) -> Image.Image:
    """Remove only the edge-connected black background from the imagegen icon."""
    src = ImageOps.fit(Image.open(SRC_ICON).convert("RGB"), (size, size), method=Image.Resampling.LANCZOS)
    if safe:
        inner = round(size * (1 - safe * 2))
        resized = ImageOps.contain(src, (inner, inner), Image.Resampling.LANCZOS)
        canvas = Image.new("RGB", (size, size), BG)
        canvas.paste(resized, ((size - resized.width) // 2, (size - resized.height) // 2))
        src = canvas

    w, h = src.size
    pixels = src.load()

    # Build a conservative candidate map for the outer black background.
    # The dark rounded tile inside the icon is protected because it is not
    # connected to the image edge through similarly dark pixels once the border
    # and highlights are reached.
    candidates = bytearray(w * h)
    for y in range(h):
        for x in range(w):
            r, g, b = pixels[x, y]
            lum = 0.2126 * r + 0.7152 * g + 0.0722 * b
            chroma = max(r, g, b) - min(r, g, b)
            cyan_bias = b - r
            if lum < 34 and chroma < 18 and cyan_bias < 16:
                candidates[y * w + x] = 1

    from collections import deque

    visited = bytearray(w * h)
    q: deque[tuple[int, int]] = deque()
    for x in range(w):
        for y in (0, h - 1):
            idx = y * w + x
            if candidates[idx] and not visited[idx]:
                visited[idx] = 1
                q.append((x, y))
    for y in range(h):
        for x in (0, w - 1):
            idx = y * w + x
            if candidates[idx] and not visited[idx]:
                visited[idx] = 1
                q.append((x, y))

    while q:
        x, y = q.popleft()
        for nx, ny in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
            if 0 <= nx < w and 0 <= ny < h:
                idx = ny * w + nx
                if candidates[idx] and not visited[idx]:
                    visited[idx] = 1
                    q.append((nx, ny))

    bg_mask = Image.frombytes("L", (w, h), bytes(255 if v else 0 for v in visited))
    bg_mask = bg_mask.filter(ImageFilter.GaussianBlur(max(0.35, size / 900)))

    alpha = ImageOps.invert(bg_mask.point(lambda p: 255 if p > 4 else 0))
    alpha = alpha.filter(ImageFilter.GaussianBlur(max(0.25, size / 1600)))

    # Preserve the inner rounded workout-card shape, which is intentionally
    # dark and should remain part of the icon after the outside background goes
    # transparent.
    card_mask = Image.new("L", (w, h), 0)
    cd = ImageDraw.Draw(card_mask)
    cd.rounded_rectangle(
        (
            round(w * 0.188),
            round(h * 0.142),
            round(w * 0.814),
            round(h * 0.850),
        ),
        radius=round(w * 0.082),
        fill=255,
    )
    alpha = Image.composite(Image.new("L", (w, h), 255), alpha, card_mask)

    out = src.convert("RGBA")
    out.putalpha(alpha)
    if rgb:
        matte = Image.new("RGB", (size, size), BG)
        matte.paste(out, mask=out.getchannel("A"))
        return matte
    return out


def save_icons() -> None:
    play_icon = icon_cutout(512)
    play_icon.save(ROOT / "store_assets/google_play/app_icon_512.png")
    play_icon.save(ROOT / "store_assets/google_play/app_icon_transparent_512.png")
    icon_cutout(1024).save(ROOT / "assets/brand/workout_notes_icon_1024.png")
    icon_cutout(512).save(ROOT / "assets/brand/workout_notes_icon_512.png")
    icon_canvas(512, rgb=True).save(ROOT / "assets/brand/workout_notes_icon_512_with_background.png")

    android = {
        "mipmap-mdpi": 48,
        "mipmap-hdpi": 72,
        "mipmap-xhdpi": 96,
        "mipmap-xxhdpi": 144,
        "mipmap-xxxhdpi": 192,
    }
    for folder, size in android.items():
        icon_canvas(size, rgb=True).save(ROOT / f"android/app/src/main/res/{folder}/ic_launcher.png")

    android_foreground = {
        "mipmap-mdpi": 108,
        "mipmap-hdpi": 162,
        "mipmap-xhdpi": 216,
        "mipmap-xxhdpi": 324,
        "mipmap-xxxhdpi": 432,
    }
    for folder, size in android_foreground.items():
        icon_cutout(size).save(ROOT / f"android/app/src/main/res/{folder}/ic_launcher_foreground.png")

    for size in [192, 512]:
        icon_cutout(size, safe=0.03).save(ROOT / f"web/icons/Icon-{size}.png")
        icon_cutout(size, safe=0.13).save(ROOT / f"web/icons/Icon-maskable-{size}.png")
    icon_cutout(64, safe=0.06).save(ROOT / "web/favicon.png")

    ios_dir = ROOT / "ios/Runner/Assets.xcassets/AppIcon.appiconset"
    with open(ios_dir / "Contents.json", "r", encoding="utf-8") as f:
        contents = json.load(f)
    for item in contents["images"]:
        filename = item.get("filename")
        if not filename:
            continue
        pt_size = float(item["size"].split("x")[0])
        scale = int(item["scale"].replace("x", ""))
        icon_canvas(round(pt_size * scale), safe=0.03, rgb=True).save(ios_dir / filename)

def launch_image(size: int) -> Image.Image:
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    icon = icon_cutout(round(size * 0.72), safe=0.02)
    glow = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    gd = ImageDraw.Draw(glow)
    pad = round(size * 0.12)
    gd.ellipse((pad, pad, size - pad, size - pad), fill=(*CYAN, 42))
    glow = glow.filter(ImageFilter.GaussianBlur(max(8, size // 16)))
    img.alpha_composite(glow)
    img.alpha_composite(icon, ((size - icon.width) // 2, (size - icon.height) // 2))
    return img


def save_launch_assets() -> None:
    android = {
        "mipmap-mdpi": 144,
        "mipmap-hdpi": 216,
        "mipmap-xhdpi": 288,
        "mipmap-xxhdpi": 432,
        "mipmap-xxxhdpi": 576,
    }
    for folder, size in android.items():
        launch_image(size).save(ROOT / f"android/app/src/main/res/{folder}/launch_image.png")

    ios_dir = ROOT / "ios/Runner/Assets.xcassets/LaunchImage.imageset"
    for filename, size in [
        ("LaunchImage.png", 168),
        ("LaunchImage@2x.png", 336),
        ("LaunchImage@3x.png", 504),
    ]:
        launch_image(size).save(ios_dir / filename)


def feature_graphic() -> None:
    img = fit(SRC_FEATURE, (1024, 500))
    img = overlay_gradient(img, 220, 20)
    img = add_vignette(img, 80)
    d = ImageDraw.Draw(img)

    text(d, (70, 142), "Workout Notes", 62, TEXT, True)
    paragraph(
        d,
        (74, 228),
        "Treinos, séries, progresso e medidas em um diário escuro, rápido e completo.",
        29,
        430,
        MUTED,
    )
    rounded(d, (74, 388, 356, 444), 18, (0, 95, 115, 220), (95, 201, 239, 95), 1)
    text(d, (215, 416), "Log. Track. Evolve.", 22, TEXT, True, "mm")
    img.convert("RGB").save(ROOT / "store_assets/google_play/feature_graphic_1024x500.png")


def screenshot_background(accent=CYAN) -> Image.Image:
    img = fit(SRC_FEATURE, (1080, 1920)).filter(ImageFilter.GaussianBlur(14))
    img = Image.blend(Image.new("RGB", (1080, 1920), BG), img, 0.38).convert("RGBA")
    d = ImageDraw.Draw(img)
    for x in range(0, 1080, 72):
        d.line((x, 0, x, 1920), fill=(255, 255, 255, 10), width=1)
    for y in range(0, 1920, 72):
        d.line((0, y, 1080, y), fill=(255, 255, 255, 10), width=1)
    glow = Image.new("RGBA", (1080, 1920), (0, 0, 0, 0))
    gd = ImageDraw.Draw(glow)
    gd.ellipse((-360, 160, 620, 1140), fill=(*accent, 50))
    gd.ellipse((660, 1040, 1460, 1840), fill=(0, 95, 115, 42))
    glow = glow.filter(ImageFilter.GaussianBlur(90))
    return Image.alpha_composite(img, glow)


def header(draw: ImageDraw.ImageDraw, title: str, subtitle: str) -> None:
    text(draw, (72, 92), title, 62, TEXT, True)
    paragraph(draw, (76, 178), subtitle, 31, 820, MUTED)


def phone_shell(base: Image.Image, x: int, y: int, w: int, h: int, screen: Image.Image) -> None:
    shadow = Image.new("RGBA", base.size, (0, 0, 0, 0))
    sd = ImageDraw.Draw(shadow)
    rounded(sd, (x - 18, y - 18, x + w + 18, y + h + 18), 52, (0, 0, 0, 120))
    shadow = shadow.filter(ImageFilter.GaussianBlur(24))
    base.alpha_composite(shadow)
    d = ImageDraw.Draw(base)
    rounded(d, (x, y, x + w, y + h), 48, (12, 17, 19, 255), (55, 67, 73, 255), 2)
    rounded(d, (x + 14, y + 14, x + w - 14, y + h - 14), 36, (7, 12, 14, 255))
    screen = ImageOps.fit(screen.convert("RGB"), (w - 28, h - 28), Image.Resampling.LANCZOS)
    mask = Image.new("L", screen.size, 0)
    md = ImageDraw.Draw(mask)
    md.rounded_rectangle((0, 0, screen.width, screen.height), radius=34, fill=255)
    base.paste(screen, (x + 14, y + 14), mask)


def fake_screen(kind: str, size: tuple[int, int] = (720, 1320)) -> Image.Image:
    w, h = size
    img = Image.new("RGB", size, BG)
    d = ImageDraw.Draw(img)
    text(d, (38, 50), "Wednesday, 1 July", 34, TEXT, True)
    rounded(d, (38, 150, w - 38, 330), 32, SURFACE_2, STROKE)
    for i, (label, value, color) in enumerate([("Workouts", "0", CYAN), ("Volume", "0 kg", TEXT), ("Streak", "3 days", AMBER)]):
        cx = 74 + i * 214
        text(d, (cx, 190), value, 32, color, True)
        text(d, (cx, 240), label, 20, MUTED)
    y = 385

    if kind == "active":
        text(d, (38, y), "ACTIVE WORKOUT", 19, MUTED, True)
        y += 50
        for ex, sets in [("Bench Press", ["80 kg  x 10", "82.5 kg x 8", "85 kg  x 8"]), ("Row", ["70 kg  x 12", "75 kg  x 10"])]:
            rounded(d, (38, y, w - 38, y + 220), 28, SURFACE, STROKE)
            rounded(d, (68, y + 36, 128, y + 96), 16, (8, 74, 91))
            text(d, (158, y + 44), ex, 29, TEXT, True)
            for i, row in enumerate(sets):
                yy = y + 102 + i * 36
                text(d, (78, yy), f"{i + 1}", 20, CYAN, True)
                text(d, (128, yy), row, 20, MUTED)
            y += 250
        rounded(d, (38, h - 180, w - 38, h - 82), 28, (0, 95, 115), (95, 201, 239))
        text(d, (82, h - 148), "Finish Workout", 30, TEXT, True)

    elif kind == "progress":
        text(d, (38, y), "PROGRESS", 19, MUTED, True)
        y += 48
        rounded(d, (38, y, w - 38, y + 390), 30, SURFACE, STROKE)
        pts = [(92, y + 310), (160, y + 260), (228, y + 280), (296, y + 190), (364, y + 214), (432, y + 132), (500, y + 156), (568, y + 88)]
        d.line(pts, fill=CYAN, width=8, joint="curve")
        for px, py in pts:
            d.ellipse((px - 9, py - 9, px + 9, py + 9), fill=AMBER)
        text(d, (74, y + 40), "Volume trend", 30, TEXT, True)
        text(d, (74, y + 86), "Last 12 weeks", 22, MUTED)
        y += 430
        for title, val in [("Frequency", "4x week"), ("Personal records", "8 PRs"), ("Cardio", "22.4 km")]:
            rounded(d, (38, y, w - 38, y + 116), 24, SURFACE, STROKE)
            text(d, (76, y + 30), title, 25, TEXT, True)
            text(d, (w - 210, y + 32), val, 27, CYAN, True)
            y += 142

    elif kind == "routines":
        text(d, (38, y), "ROUTINES", 19, MUTED, True)
        y += 48
        for title, detail in [("Push Day", "5 exercises • 18 sets"), ("Pull Day", "6 exercises • 21 sets"), ("Legs + Core", "7 exercises • 24 sets"), ("Cardio", "3 exercises • 45 min")]:
            rounded(d, (38, y, w - 38, y + 132), 26, SURFACE, STROKE)
            rounded(d, (68, y + 34, 126, y + 92), 16, (8, 74, 91))
            text(d, (156, y + 32), title, 30, TEXT, True)
            text(d, (156, y + 76), detail, 22, MUTED)
            text(d, (w - 88, y + 50), ">", 32, TEXT)
            y += 158

    else:
        text(d, (38, y), "BODY MEASUREMENTS", 19, MUTED, True)
        y += 48
        rounded(d, (38, y, w - 38, y + 210), 30, SURFACE, STROKE)
        text(d, (76, y + 42), "Body weight", 28, MUTED)
        text(d, (76, y + 88), "78.4 kg", 54, CYAN, True)
        text(d, (76, y + 154), "+1.8 kg this month", 22, AMBER, True)
        y += 258
        for title, val in [("Waist", "82 cm"), ("Chest", "104 cm"), ("Arm", "38 cm"), ("Body fat", "14.8%")]:
            rounded(d, (38, y, w - 38, y + 106), 24, SURFACE, STROKE)
            text(d, (76, y + 31), title, 26, TEXT, True)
            text(d, (w - 176, y + 31), val, 26, CYAN, True)
            y += 130

    return img


def screenshot_actual() -> None:
    base = screenshot_background(CYAN)
    d = ImageDraw.Draw(base)
    header(d, "Seu treino em ordem", "A tela inicial segue o visual real do app: dark, compacta e pronta para registrar.")
    reference = Image.open(SRC_REFERENCE).convert("RGB")
    phone_shell(base, 190, 380, 700, 1430, reference)
    base.convert("RGB").save(ROOT / "store_assets/screenshots/01_dashboard_real_1080x1920.png")


def screenshot_mock(filename: str, title: str, subtitle: str, kind: str, accent=CYAN) -> None:
    base = screenshot_background(accent)
    d = ImageDraw.Draw(base)
    header(d, title, subtitle)
    phone_shell(base, 180, 392, 720, 1390, fake_screen(kind))
    base.convert("RGB").save(ROOT / f"store_assets/screenshots/{filename}")


def screenshots() -> None:
    screenshot_actual()
    screenshot_mock("02_active_workout_1080x1920.png", "Registre sem fricção", "Peso, reps, descanso e séries em uma tela feita para usar no treino.", "active", CYAN)
    screenshot_mock("03_progress_1080x1920.png", "Veja sua evolução", "Volume, frequência, cardio e recordes com leitura rápida.", "progress", CYAN)
    screenshot_mock("04_routines_1080x1920.png", "Rotinas reutilizáveis", "Monte seus dias de treino e comece a sessão com menos toque.", "routines", AMBER)
    screenshot_mock("05_body_tracker_1080x1920.png", "Acompanhe medidas", "Peso, cintura, fotos e tendências junto do histórico de treino.", "body", CYAN)


def docs() -> None:
    guide = """# Workout Notes - Identidade visual

## Direcao
A nova identidade foi criada a partir da screenshot real do app e das imagens geradas com $imagegen. O visual agora segue o produto atual: fundo quase preto, superficies grafite, cards arredondados, tipografia clara e acentos cyan com detalhe ambar para streak/energia.

## Paleta
- Background: #090E10
- Surface: #151B1E
- Raised surface: #1F262B
- Divider: #293237
- Primary cyan: #6CCFF6
- Deep cyan: #005F73
- Amber highlight: #FFB000
- Text: #DEE5E9
- Muted text: #A6B1B8

## Marca
O icone combina ficha de treino, check de conclusao e halteres. Ele comunica registro, treino concluido e progresso sem usar letras.

## Assets gerados
- `store_assets/google_play/app_icon_512.png`
- `store_assets/google_play/app_icon_transparent_512.png`
- `store_assets/google_play/feature_graphic_1024x500.png`
- `store_assets/screenshots/*.png`
- `assets/brand/workout_notes_icon_512.png`
- `assets/brand/workout_notes_icon_1024.png`
- `android/app/src/main/res/mipmap-*/launch_image.png`
- `ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage*.png`

## Prompts usados no $imagegen
Os prompts priorizaram: dark graphite/cyan Material 3, cards densos, dashboard tecnico de treino, sem texto gerado, sem pessoas, sem estetica generica de academia.
"""
    (ROOT / "store_assets/brand_guide.md").write_text(guide, encoding="utf-8")

    pt = """# Google Play - Listing pt-BR

## Nome
Workout Notes

## Descricao curta
Diario dark para registrar treinos, series, rotinas e progresso.

## Descricao completa
Workout Notes e um diario de treino completo, feito para registrar suas sessoes com rapidez e acompanhar sua evolucao com clareza.

Use durante o treino para anotar exercicios, series, peso, repeticoes, distancia, tempo, RPE e observacoes. Crie rotinas reutilizaveis, veja seu historico em calendario, acompanhe graficos de volume e frequencia, registre medidas corporais e exporte seus dados quando precisar.

Recursos principais:
- Treino ativo com timer de sessao e descanso entre series
- Biblioteca de exercicios organizada por grupos e sistema energetico
- Quick Add para registrar series rapidamente
- Rotinas para repetir treinos com menos toque
- Graficos de volume, frequencia, cardio e recordes pessoais
- Historico de treinos com calendario
- Medidas corporais, fotos e tendencias
- Backup completo em JSON e exportacao CSV
- Tema claro/escuro e cores de destaque personalizaveis

Workout Notes foi pensado para quem quer treinar com intencao: menos improviso, mais historico e uma leitura visual do proprio progresso.
"""
    (ROOT / "store_assets/google_play/store_listing_pt_BR.md").write_text(pt, encoding="utf-8")

    en = """# Google Play - Listing en-US

## App name
Workout Notes

## Short description
Dark workout journal for sets, routines, progress and body stats.

## Full description
Workout Notes is a complete workout journal designed for fast session logging and clear progress tracking.

Log exercises, sets, weight, reps, distance, time, RPE and notes during your workout. Build reusable routines, review history on a calendar, follow volume and frequency charts, track body measurements and export your data whenever needed.

Main features:
- Active workout logging with workout and rest timers
- Exercise library organized by muscle group and energy system
- Quick Add for fast set logging
- Reusable routines for faster sessions
- Progress charts for volume, frequency, cardio and personal records
- Workout calendar and completed session history
- Body measurements, photos and trends
- Complete JSON backup and CSV export
- Light/dark theme with customizable accent colors
"""
    (ROOT / "store_assets/google_play/store_listing_en_US.md").write_text(en, encoding="utf-8")


def main() -> None:
    ensure_dirs()
    save_icons()
    save_launch_assets()
    feature_graphic()
    screenshots()
    docs()


if __name__ == "__main__":
    main()
